const root = [
  {
    id: "introduction",
    title: "Introduction",
    date: "2024-02-24",
    parent: null,
    order: 1,
    author: "Alex B",
    category: "General",
    tags: ["intro", "getting-started"],
  },
  {
    id: "quick-start",
    title: "Quick Start",
    date: "2024-02-24",
    parent: null,
    order: 2,
    author: "Brian C",
    category: "quick-start",
    tags: ["intro", "getting-started"],
  },
  {
    id: "sdks",
    title: "SDKs",
    date: "2024-02-24",
    parent: null,
    order: 3,
    author: "Brian C",
    category: "sdk",
    tags: ["technology"],
  },
  {
    id: "analysis",
    title: "Analysis",
    date: "2024-02-24",
    parent: null,
    order: 4,
    author: "Brain C",
    category: "analytics",
    tags: ["technology", "analytics"],
  },
  {
    id: "resources",
    title: "Resourses",
    date: "2024-02-24",
    parent: "introduction",
    author: "Lenevoiya",
    category: "resources",
    tags: ["getting-started"],
  },
  {
    id: "test",
    title: "Test",
    date: "2024-02-24",
    parent: "introduction",
    author: "Brian C",
    category: "testing",
    tags: ["test", "technology"],
  },
];
